version: 2
updates:
  - package-ecosystem: "pip"
    directory: "/"
    schedule:
      interval: "weekly"
    cooldown:
      semver-patch-days: 2
      semver-minor-days: 5
      semver-major-days: 10
    commit-message:
      prefix: "[MAINTENANCE PIP] - "
    assignees:
      - "TobiKuehn7"
    labels:
      - "dependency update"
      - "maintenance"

  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
    commit-message:
      prefix: "[MAINTENANCE GIT] - "
    assignees:
      - "TobiKuehn7"
    labels:
      - "dependency update"
      - "maintenance"
