name: Python packaging

on:
  workflow_dispatch:

jobs:
  # Test job
#  test:
#    runs-on: ubuntu-latest
#    steps:
#      - name: Checkout repository
#        uses: actions/checkout@v2
#
#      - name: Set up Python
#        uses: actions/setup-python@v2
#        with:
#          python-version: '3.12'  # You can change this to your desired Python version
#
#      - name: Install dependencies
#        run: |
#          python -m pip install --upgrade pip
#          pip install -r requirements.txt
#
#      - name: Run tests
#        run: |
#          pytest tests/

  # Build job
  build:
    runs-on: ubuntu-latest
    needs: test  # Ensure the tests pass before continuing with build
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.12'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Build package
        run: |
          python setup.py sdist bdist_wheel

  # Deploy job (upload to TestPyPI first)
  deploy:
    runs-on: ubuntu-latest
    needs: build  # Ensure build passes before deploy
    if: github.ref == 'refs/heads/master'  # Only deploy from the master branch
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.12'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install twine

      - name: Upload package to TestPyPI
        run: |
          twine upload --repository-url https://test.pypi.org/legacy/ dist/*

  # Deploy to PyPI (optional, after successful TestPyPI deployment)
  deploy_prod:
    runs-on: ubuntu-latest
    needs: deploy  # Ensure TestPyPI deploy passes before deploying to PyPI
    if: github.ref == 'refs/heads/master'  # Only deploy from the master branch
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.12'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install twine

      - name: Upload package to PyPI
        run: |
          twine upload dist/*
